name: Hotlink
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4732920222450048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ea1e2d'
    - '#ffffff'
    - '#1b8345'
    - '#08080a'
    - '#efb631'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6723166001029313
  rhythmicContrast: 0.25
purpose: []
